const services = [
    {
      id: "accounting",
      name: "Accounting and Audit",
      description: [
        "Statutory Audit",
        "Tax Audit ((Under Section 44AB of the Income Tax Act)",
        "Audit (Under Miscellaneous Sections of Income Tax Act 1961 such as Section 80 HHC, 80 IA ect.)",
        "Due Diligence",
        "Investigation",
        "Stock Audit",
        "Concurrent Audit",
      ],
    },
    {
      id: "corporate",
      name: "Corporate Consultancy",
      description: [
        "Mergers, Acquisitions, Demergers and Corporate Restructuring",
        "Corporate Law Matters",
        "Valuations",
        "Compliance of Clause 49",
        "Corporate Governance",
        "Private Equity (PE)",
        "Debt / Equity Placement",
        "Joint Ventures",
      ],
    },
    {
      id: "advisory",
      name: "Business Advisory & Assurance",
      description: [
        "Internal Audit",
        "Information System Audit",
        "Operations Audit",
        "Risk Assessment",
        "SOPS Development",
        "Fixed Assets Management",
      ],
    },
    {
      id: "taxation",
      name: "International Taxation",
      description: [
        "Transfer Pricing",
        "Expatriate Tax",
        "Double Tax Avoidance Agreement (DTAA)",
        "Representation before Dispute Resolution Panel (DRP)",
        "Representation before Authority for Advance Rulings (AAR)",
        "Cross Border Transaction Structuring",
      ],
    },
    {
      id: "fema",
      name: "Foreign Exchange Management Act (FEMA)",
      description: [
        "Stratgem for",
        "Liaison Offices (LO)",
        "Branch Offices",
        "Project Offices",
        "Subsidiaries",
        "Joint Ventures",
        "RBI Representation",
        "Foreign Direct Investments",
        "Foreign Exchange Management Act, 1999 (FEMA)",
        "Obtaining approvals under FEMA from RBI and FIPB and compliance thereof",
      ],
    },
    {
      id: "finance",
      name: "Management Advisory & Finance",
      description: [
        "Business Plans & Financing Proposals",
        "Forecast & Projections",
        "Systems and Consultancy Services",
        "Transaction Services",
        "Loan Syndication",
        "MIS",
        "Management Accounting and Profit Control",
        "Financial Analysis, Reporting and Budgeting",
        "Project Financing",
        "Funding from Venture Capitalist",
      ],
    },
    {
      id: "domestic",
      name: "Domestic Taxation",
      description: [
        "Income Tax Compliance",
        "Income Tax Planning for Corporates & Others",
        "Effective Tax Management & Tax Structuring",
        "Income Tax Representation Services (Including before ITAT)",
        "Income Tax Advisory",
        "GOODS & SERVICES TAX (GST)",
        "GST Registration",
        "GST Compliance",
        "GST Representation Services",
        "GST Advisory",
        "GST Audit",
      ],
    },
    {
      id: "analytics",
      name: "Business Analytics",
      description: [
        "Measure financial performance",
        "Identify weakness in financial processes",
        "Meaningful data for future growth",
        "Financial planning",
      ],
    },
  ];
  
  export default services;
  